export enum MediaType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO'
}

export interface MediaAsset {
  file: File;
  previewUrl: string;
  type: MediaType;
  base64?: string;
  mimeType: string;
}

export interface Message {
  id: string;
  role: 'user' | 'model';
  content: string;
  timestamp: number;
  isThinking?: boolean;
  generatedImage?: string; // Base64 string of image generated by code execution (deprecated)
  visualizations?: VisualizationSpec[];
}

export interface AnalysisState {
  isAnalyzing: boolean;
  currentPhase: string; // e.g., "Uploading", "Processing Vision", "Executing Code", "Finalizing"
}

// ============================================
// Simplified Visualization Types
// Focus on lines, paths, and arrows - not player identification
// ============================================

// Normalized position (0-100 scale)
export interface Position {
  x: number;  // 0=left, 100=right
  y: number;  // 0=top, 100=bottom
}

// Attack line - shows offensive movement or ball path
export interface AttackLine {
  id: string;
  from: Position;
  to: Position;
  label?: string;  // e.g., "Pass", "Drive", "Cut"
  style?: 'solid' | 'dashed' | 'dotted';
}

// Defense line - shows defensive positioning or coverage
export interface DefenseLine {
  id: string;
  from: Position;
  to: Position;
  label?: string;  // e.g., "Help", "Switch", "Close out"
  style?: 'solid' | 'dashed' | 'dotted';
}

// Movement path - shows potential or historical movement
export interface MovementPath {
  id: string;
  points: Position[];  // Path of movement
  type: 'attack' | 'defense' | 'neutral';
  label?: string;  // e.g., "Player movement", "Predicted path"
  style?: 'solid' | 'dashed' | 'dotted';
}

// Zone/Region - highlight an area of interest
export interface ZoneRegion {
  id: string;
  points: Position[];  // Polygon points
  label?: string;  // e.g., "Gap", "Open space", "Weak side"
  type: 'attack' | 'defense' | 'neutral';
}

// Annotation - text label at a position
export interface Annotation {
  id: string;
  position: Position;
  text: string;
}

// Play Diagram - the main visualization spec
export interface PlayDiagramSpec {
  type: 'play_diagram';
  title?: string;
  description?: string;
  attackLines?: AttackLine[];
  defenseLines?: DefenseLine[];
  movementPaths?: MovementPath[];
  zones?: ZoneRegion[];
  annotations?: Annotation[];
}

export type VisualizationSpec = PlayDiagramSpec;

// ============================================
// Agentic Tool-Calling Types
// ============================================

export type OverlayStage = 'capture' | 'think' | 'diagram' | 'finalize';

// Partial overlay - can include any subset of visualization elements
export interface OverlayData {
  attackLines?: AttackLine[];
  defenseLines?: DefenseLine[];
  movementPaths?: MovementPath[];
  zones?: ZoneRegion[];
  annotations?: Annotation[];
}

export interface ShowOverlayArgs {
  id: string;                 // Unique identifier
  overlay: OverlayData;       // Visual elements to add/display
  thinking: string;           // One-line reasoning
  stage?: OverlayStage;       // UI styling hint
}

export interface ToolCallEvent {
  type: 'tool_call';
  toolName: string;
  args: ShowOverlayArgs;
}

export interface CompletionEvent {
  type: 'completion';
  finalText: string;
}

export type AgentEvent = ToolCallEvent | CompletionEvent;
export type AgentCallback = (event: AgentEvent) => void;

// Thinking step for progress display
export interface ThinkingStep {
  id: string;
  thinking: string;
  stage?: OverlayStage;
}