export enum MediaType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO'
}

export interface MediaAsset {
  file: File;
  previewUrl: string;
  type: MediaType;
  base64?: string;
  mimeType: string;
}

export interface Message {
  id: string;
  role: 'user' | 'model';
  content: string;
  timestamp: number;
  isThinking?: boolean;
  generatedImage?: string; // Base64 string of image generated by code execution (deprecated)
  visualizations?: VisualizationSpec[]; // Remotion visualization specs
}

export interface AnalysisState {
  isAnalyzing: boolean;
  currentPhase: string; // e.g., "Uploading", "Processing Vision", "Executing Code", "Finalizing"
}

// ============================================
// Remotion Visualization Types
// ============================================

// Normalized court position (0-100 scale)
export interface CourtPosition {
  x: number;  // 0=left baseline, 100=right
  y: number;  // 0=bottom sideline, 100=top
}

export interface PlayerMarker {
  id: string;
  position: CourtPosition;
  team: 'offense' | 'defense' | 'neutral';
  jerseyNumber?: number;
  label?: string;
  hasBall?: boolean;
}

export interface MovementArrow {
  id: string;
  from: CourtPosition;
  to: CourtPosition;
  color?: string;
  dashed?: boolean;
  label?: string;
}

export interface CourtAnnotation {
  id: string;
  position: CourtPosition;
  text: string;
  color?: string;
}

export interface BoundingBox {
  id: string;
  x: number;      // 0-100 normalized
  y: number;      // 0-100 normalized
  width: number;  // 0-100 normalized
  height: number; // 0-100 normalized
  label?: string;
  team?: 'home' | 'away' | 'neutral';
  confidence?: number;
}

export interface PlayerTrajectory {
  id: string;
  playerId: string;
  points: CourtPosition[];
  team: 'offense' | 'defense' | 'neutral';
  label?: string;
}

export interface SpacingMetric {
  id: string;
  from: CourtPosition;
  to: CourtPosition;
  distance: number; // in feet
  label?: string;
  isOptimal?: boolean;
}

// Visualization Specs
export interface CourtDiagramSpec {
  type: 'court_diagram';
  title?: string;
  players: PlayerMarker[];
  formationLabel?: string;
  arrows?: MovementArrow[];
  annotations?: CourtAnnotation[];
}

export interface TrackingOverlaySpec {
  type: 'tracking_overlay';
  boundingBoxes: BoundingBox[];
  teamColors?: { home: string; away: string };
}

export interface TrajectorySpec {
  type: 'trajectory';
  title?: string;
  trajectories: PlayerTrajectory[];
  animatePlayback?: boolean;
}

export interface SpacingAnalysisSpec {
  type: 'spacing_analysis';
  title?: string;
  players: PlayerMarker[];
  spacingMetrics?: SpacingMetric[];
  spacingGrade?: 'A' | 'B' | 'C' | 'D' | 'F';
}

export type VisualizationSpec =
  | CourtDiagramSpec
  | TrackingOverlaySpec
  | TrajectorySpec
  | SpacingAnalysisSpec;